# Generated by Django 5.2.8 on 2025-11-19 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('color_primary', models.CharField(default='#000000', max_length=7)),
                ('color_secondary', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('DUELIST', 'Duelist'), ('INITIATOR', 'Initiator'), ('CONTROLLER', 'Controller'), ('SENTINEL', 'Sentinel')], max_length=20)),
                ('rating', models.IntegerField(default=75)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.team')),
            ],
        ),
    ]
