# Generated by Django 5.2.8 on 2025-11-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
    ]
