# Generated by Django 5.2.8 on 2025-11-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_championship_map_match_championship_match_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['region', 'name']},
        ),
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.CharField(choices=[('AMERICAS', 'Americas'), ('EMEA', 'EMEA'), ('PACIFIC', 'Pacific'), ('CHINA', 'China')], default='AMERICAS', max_length=20),
        ),
    ]
