# Generated by Django 5.2.8 on 2025-11-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_team_options_team_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aim',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='clutch',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='gamesense',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='support',
            field=models.IntegerField(default=10),
        ),
    ]
