# Generated by Django 5.2.8 on 2025-11-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_aim_player_clutch_player_gamesense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mental',
            field=models.IntegerField(default=10),
        ),
    ]
